# Spring Boot configuration
spring:
  profiles:
    active: development
  application:
    name: job-service
  datasource:   # Database
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/JobSearchApp
    username: root
    password: root
  jpa: # JPA properties
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

# Server configuration
server:
  port: 8081 #set your port
## Logger configuration
#logging:
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#  level:
#    org.springframework: info
#    org.hibernate: debug

# Security configuration
#  security:
#    user:
#      name: user
#      password: user



#Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: